### ISSUE TITLE
没有创建目录的权限 mkdir(): Permission denied

### ISSUE THREAD

**Issue by fengke549015** [exc-soft/docker-lnmp#4]
想问一下，我创建成功，项目也搭建成功能够正常运行了，但是进行PHP项目图片上传的时候和创建PHP项目日志文件的时候，报没有创建目录的权限，这种情况应该怎么做呢？

**Comment by cuiziwei** [comment]
@fengke549015 给容器外面的上传目录权限就行了

**Comment by fengke549015** [comment]
@cuiziwei 我是windows下的 docker-desktop  我已经给了外面的权限，也通过nginx 和php都进行privileged启动，进入容器给里面的目录相对应的权限了，还是会报权限不足呢

**Comment by cuiziwei** [comment]
@fengke549015 印象好像遇到过你这种，升级了 docker 就好了，不知道是不是版本问题，我没用过 windows 下面的，建议还是 linux ~
